# Generated by Django 4.0.3 on 2022-09-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
